name: Greetings

on:
  pull_request:
    branches:
    - master

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
	pr-message: 'Message that will be displayed when a user sets up pull request into master' Greetings, thanks $GITHUB_ACTOR for the pull request :)

