name: Greetings

on:
  push:
    branches:
      - master

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        pr-message: 'Greetings, thanks $GITHUB_ACTOR for the pull request :)'
	issue-message: 'Greetings, thanks $GITHUB_ACTOR for raising an issue :)'  
